// <auto-generated />
using System;
using Frontline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frontline.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20240731164443_GuildXpGift")]
    partial class GuildXpGift
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Frontline.Data.Entities.ActiveMissionEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("MissionKey")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Bonus1Casualty")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Bonus1Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Bonus2Casualty")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Bonus2Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("BonusCard1ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("BonusCard2ItemId")
                        .HasColumnType("int");

                    b.Property<bool>("Casualty")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RequiredCardItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId", "MissionKey");

                    b.HasIndex("UserId", "BonusCard1ItemId");

                    b.HasIndex("UserId", "BonusCard2ItemId");

                    b.HasIndex("UserId", "RequiredCardItemId");

                    b.ToTable("ActiveMissions");
                });

            modelBuilder.Entity("Frontline.Data.Entities.FinishedMissionEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("MissionKey")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "MissionKey");

                    b.ToTable("FinishedMissions");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Locale")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumberOfMembers")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildMemberEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<Guid>("GuildId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ItemEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<bool>("Casualty")
                        .HasColumnType("tinyint(1)");

                    b.Property<sbyte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Frontline.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("BoosterPackCount")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("DropshipId")
                        .HasColumnType("int");

                    b.Property<int>("HighestTrophies")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastGiftSent")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("MissionsComplete")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<int>("Supply")
                        .HasColumnType("int");

                    b.Property<int>("Tokens")
                        .HasColumnType("int");

                    b.Property<int>("Trophies")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ActiveMissionEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontline.Data.Entities.ItemEntity", "BonusCard1Item")
                        .WithMany()
                        .HasForeignKey("UserId", "BonusCard1ItemId");

                    b.HasOne("Frontline.Data.Entities.ItemEntity", "BonusCard2Item")
                        .WithMany()
                        .HasForeignKey("UserId", "BonusCard2ItemId");

                    b.HasOne("Frontline.Data.Entities.ItemEntity", "RequiredCardItem")
                        .WithMany()
                        .HasForeignKey("UserId", "RequiredCardItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusCard1Item");

                    b.Navigation("BonusCard2Item");

                    b.Navigation("Player");

                    b.Navigation("RequiredCardItem");
                });

            modelBuilder.Entity("Frontline.Data.Entities.FinishedMissionEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildMemberEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.GuildEntity", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ItemEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
