// <auto-generated />
using System;
using Frontline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Frontline.Data.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260425025221_CorrectMessageLength")]
    partial class CorrectMessageLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frontline.Data.Entities.ActiveMissionEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("MissionKey")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<bool>("Bonus1Casualty")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bonus1Success")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bonus2Casualty")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bonus2Success")
                        .HasColumnType("boolean");

                    b.Property<int?>("BonusCard1ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("BonusCard2ItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Casualty")
                        .HasColumnType("boolean");

                    b.Property<int>("RequiredCardItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<bool>("Synergy1Success")
                        .HasColumnType("boolean");

                    b.Property<bool>("Synergy2Success")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "MissionKey");

                    b.HasIndex("UserId", "BonusCard1ItemId");

                    b.HasIndex("UserId", "BonusCard2ItemId");

                    b.HasIndex("UserId", "RequiredCardItemId");

                    b.ToTable("ActiveMissions");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ChatMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(41)
                        .HasColumnType("character varying(41)");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Frontline.Data.Entities.DropshipEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DropshipId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DropshipId", "SlotIndex");

                    b.HasIndex("UserId", "ItemId");

                    b.ToTable("Dropships");
                });

            modelBuilder.Entity("Frontline.Data.Entities.FinishedMissionEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("MissionKey")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.HasKey("UserId", "MissionKey");

                    b.ToTable("FinishedMissions");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Locale")
                        .HasColumnType("integer");

                    b.Property<int>("MaxNumberOfMembers")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildMemberEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ItemEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Casualty")
                        .HasColumnType("boolean");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Frontline.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("BoosterPackCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ChatBanEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<int>("DropshipId")
                        .HasColumnType("integer");

                    b.Property<int>("HighestTrophies")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastGiftSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSupplySync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MissionsComplete")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<int>("Supply")
                        .HasColumnType("integer");

                    b.Property<int>("Tokens")
                        .HasColumnType("integer");

                    b.Property<int>("Trophies")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ActiveMissionEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontline.Data.Entities.ItemEntity", "BonusCard1Item")
                        .WithMany()
                        .HasForeignKey("UserId", "BonusCard1ItemId");

                    b.HasOne("Frontline.Data.Entities.ItemEntity", "BonusCard2Item")
                        .WithMany()
                        .HasForeignKey("UserId", "BonusCard2ItemId");

                    b.HasOne("Frontline.Data.Entities.ItemEntity", "RequiredCardItem")
                        .WithMany()
                        .HasForeignKey("UserId", "RequiredCardItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusCard1Item");

                    b.Navigation("BonusCard2Item");

                    b.Navigation("Player");

                    b.Navigation("RequiredCardItem");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.DropshipEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontline.Data.Entities.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("UserId", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.FinishedMissionEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildMemberEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.GuildEntity", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.ItemEntity", b =>
                {
                    b.HasOne("Frontline.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Frontline.Data.Entities.GuildEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
